### ISSUE TITLE
Test MAUI sample

### ISSUE THREAD

**Issue by if-mindesk** [ab4d/Ab4d.SharpEngine.Samples#16]
Hi,
I would like to test the MAUI sample.
Do I need a trial license or something else?

Thank you

**Comment by abenedik** [comment]
The samples in this repo already have a special samples license key applied so you can just start them. 

But if you would like to create your own app, then you would first need a trial license (can be get from https://ab4d.com/trial) and later a commercial license.

**Comment by if-mindesk** [comment]
Thanks for the info.
I tested the MAUI sample and it runs fine on Windows and on Android physical device.
It crashes with Android emulator 
![image](https://github.com/user-attachments/assets/e3b91a6a-bd1b-48e6-9b03-64047df80fde)

![image](https://github.com/user-attachments/assets/ff7b442b-3076-48ca-aaa2-9aadb787f83f)

**Comment by abenedik** [comment]
I would like to inform you that the new beta version (2.1.9028-beta1) runs correctly in Android emulator.
You can get the beta version from the NuGet package.

See screenshot:
![image](https://github.com/user-attachments/assets/a4a372e0-aae7-4893-a286-c8c7f98601f7)
