### ISSUE TITLE
IMGUI Sample - docking SharpEngine into IMGUI panel or window

### ISSUE THREAD

**Issue by stephensmitchell** [ab4d/Ab4d.SharpEngine.Samples#21]
Is it possible to render SharpEngine inside an IMGUI panel or window instead of IMGUI being rendered on top of the SharpEngine view? Any examples or the steps needed to make this work? Thanks

**Comment by abenedik** [comment]
IMGUI cannot render itself - it only provides a vertex buffer, index buffer and one font texture. This then needs to be rendered by a third-party rendering engine.

It would be possible to render 3D scene by SharpEngine to a shared texture that would be shared with some other rendering engine that would also render ImGui. But this would require 2 rendering engines and 2 graphics devices - so much more resources. Therefore, it is usually better to use only one rendering engine.

**Comment by stephensmitchell** [comment]
Is it possible to split the window/view a percentage and have for example SharpEngine on the left side and imgui on the right side? I want to build an app where imgui is fixed on one side and never leaves or move on top off the sharpengine view. A master details view or something similar to the sharpengine examples application with a fixed list or tree view on the left and sharpengine on the right.
