### ISSUE TITLE
Add easy to see note that the SharpEngine is not free.

### ISSUE THREAD

**Issue by cyraid** [ab4d/Ab4d.SharpEngine.Samples#22]
I was pretty much settled on this project until I found out it wasn't free. It would've saved me a lot of time if a note (maybe in bold) at the beginning of the README stated Sharp Engine is NOT FREE. Perhaps put prices down? And that you need to get a license at ab4d.com/trial or ab4d.com/purchase instead of seeing it in a comment in the code?

To be clear, I'm not against selling software and having it on Github, but I'd like to know up front if it's Free/Open Source so I can keep paging through the other options in my case.

**Comment by abenedik** [comment]
I am sorry that this is not described well enough. I thought that having `Licensing.SetLicense` call and the comment "`To use Ab4d.SharpEngine in your project, get a license from ab4d.com/trial or ab4d.com/purchase`" in the samples code would be clear enough. Also, as soon as you use the library in your own project, you get license info.

However, I understand that spending hours on a project and then finding out that it is not free is not a good experience. To prevent that, I have added an additional notice to the readme as you have advised.

What is more, the next version of Ab4d.SharpEngine will provide **a free license for open-source projects**. So, if you are using the library for yourself, you will need to publish your project as an open-source project, and you will be able to use the library indefinitely (without the limited trial period). But if you use it for commercial purposes, then you will need to pay for a license. With a commercial license, you also get priority email support and other benefits (feature requests, etc.).

The next version will be available in Q1 2025 (hopefully by the end of January). Until then, please use the trial version (to get a new trial or extend it, visit [ab4d.com/trial](ab4d.com/trial)).

**Comment by cyraid** [comment]
@abenedik wow. Quick reply, understanding, and quick to action. I am impressed my friend. Very nice! You're also making a free version for open source. Good stuff!

**Comment by abenedik** [comment]
I would like to inform you that the new version 3.0 supports free open-source license. You can apply for that license [here](https://www.ab4d.com/SharpEngineLicense.aspx?opensource=1).
